// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-deep-typing-proofs.mjs.

export type DeepTypingStatus = 'ready' | 'review';

export const DEEP_TYPING_COMPILED_DEPTHS = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
] as const;
export type DeepTypingCompiledDepth =
  (typeof DEEP_TYPING_COMPILED_DEPTHS)[number];
export const DEEP_TYPING_MIN_DEPTH: DeepTypingCompiledDepth = 1;
export const DEEP_TYPING_MAX_DEPTH: DeepTypingCompiledDepth = 40;
export const DEEP_TYPING_COMPILER_CHECKS = {
  exactLocation: true,
  isAny: false,
} as const;
export const DEEP_TYPING_BRANCH_SEGMENTS = [
  'enterprise',
  'divisions',
  'technology',
  'departments',
  'engineering',
  'teams',
  'frontend',
  'projects',
  'signaltree',
  'releases',
  'v15',
  'features',
  'recursiveTyping',
  'validation',
  'branch15',
  'branch16',
  'branch17',
  'branch18',
  'branch19',
  'branch20',
  'branch21',
  'branch22',
  'branch23',
  'branch24',
  'branch25',
  'branch26',
  'branch27',
  'branch28',
  'branch29',
  'branch30',
  'branch31',
  'branch32',
  'branch33',
  'branch34',
  'branch35',
  'branch36',
  'branch37',
  'branch38',
  'branch39',
] as const;

export const isDeepTypingCompiledDepth = (
  value: number
): value is DeepTypingCompiledDepth =>
  Number.isInteger(value) &&
  value >= DEEP_TYPING_MIN_DEPTH &&
  value <= DEEP_TYPING_MAX_DEPTH;
