export const DEMO_ROUTES = [
  '/',
  '/start',
  '/why-causality',
  '/external-truth',
  '/examples/fundamentals',
  '/batching',
  '/entities',
  '/entity-sort-comparer',
  '/granular-reactivity',
  '/restoration',
  '/markers',
  '/devtools',
  '/examples/fundamentals/recommended-architecture',
  '/migrate',
  '/benchmarks',
  '/deep-typing',
  '/realistic-benchmark-history',
  '/architecture-overview',
  '/legacy-changelog',
  '/docs',
] as const;
