// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const DEMO_LIBRARY_VERSIONS: Record<string, string> = {
  signaltree: '15.0.0-rc.12',
  'ngrx-store': '21.1.1',
  'ngrx-signals': '21.1.1',
  akita: '8.0.1',
  elf: '2.5.1',
  'elf-entities': '5.0.2',
  'elf-state-history': '1.4.0',
  'redux-toolkit': '2.12.0',
  ngxs: '20.1.0',
};
