// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const SIGNALTREE_CORE_VERSION = '16.0.0';
export const SIGNALTREE_VERSION_SUMMARY = '@signal-tree/kernel v16.0.0';
